-- Migration to add missing agent address columns and verify all form fields
ALTER TABLE trademark_cases
  ADD COLUMN IF NOT EXISTS agent_country VARCHAR(100) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS agent_city VARCHAR(100) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS agent_subcity VARCHAR(100) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS agent_woreda VARCHAR(100) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS agent_house_no VARCHAR(100) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS agent_telephone VARCHAR(100) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS agent_email VARCHAR(255) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS agent_po_box VARCHAR(100) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS agent_fax VARCHAR(100) DEFAULT NULL;
